// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    [Migration("20260816151124_InitialProfiles")]
    partial class InitialProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Profiles")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Domain.ActorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlbumCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIndexable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaCount")
                        .HasColumnType("integer");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("CreatedDate", "Id")
                        .HasDatabaseName("IX_ActorProfiles_Indexable_CreatedDate")
                        .HasFilter("\"IsIndexable\"");

                    b.ToTable("ActorProfiles", "Profiles");
                });

            modelBuilder.Entity("Profiles.Domain.ActorProfile", b =>
                {
                    b.OwnsOne("Profiles.Domain.ValueObjects.ProfileSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ActorProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Slug");

                            b1.HasKey("ActorProfileId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ActorProfiles", "Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ActorProfileId");
                        });

                    b.OwnsMany("Profiles.Domain.ValueObjects.SocialLink", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("ActorProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.HasKey("ActorProfileId", "Id");

                            b1.ToTable("ActorProfiles", "Profiles");

                            b1.ToJson("SocialLinks");

                            b1.WithOwner()
                                .HasForeignKey("ActorProfileId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("SocialLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
