<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Aspire.Hosting.AppHost"/>
	<PackageReference Include="CommunityToolkit.Aspire.Hosting.NodeJS.Extensions"/>
  </ItemGroup>
</Project>