// <auto-generated />
using System;
using Host.WebApi.ArtworkViews;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Host.WebApi.ArtworkViews.Migrations
{
    [DbContext(typeof(ArtworkViewsDbContext))]
    [Migration("20260730151510_InitialArtworkViews")]
    partial class InitialArtworkViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Host.WebApi.ArtworkViews.ArtworkView", b =>
                {
                    b.Property<string>("ArtworkSlug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("artwork_slug");

                    b.Property<DateTimeOffset>("LastViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("ArtworkSlug");

                    b.ToTable("artwork_view_counts", "analytics", t =>
                        {
                            t.HasCheckConstraint("ck_artwork_view_counts_count", "view_count > 0");

                            t.HasCheckConstraint("ck_artwork_view_counts_slug", "char_length(artwork_slug) BETWEEN 1 AND 120 AND artwork_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
