<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <!-- Make [Fact] and Assert available in all test files without explicit using -->
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <!--
    One reference per module layer.
    When you add a new module (e.g. Posts), add Posts.Domain and Posts.Application here.
    The compiler will pull all assemblies into the bin folder automatically.
  -->
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernal\SharedKernal.csproj" />
    <ProjectReference Include="..\..\Users.Domain\Users.Domain.csproj" />
    <ProjectReference Include="..\..\Users.Application\Users.Application.csproj" />
    <ProjectReference Include="..\..\Users.Infrastracture\Users.Infrastracture.csproj" />
    <ProjectReference Include="..\..\Users.Presentation\Users.Presentation.csproj" />
  </ItemGroup>

</Project>
