// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260907165038_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EditorialRank")
                        .HasColumnType("integer");

                    b.Property<long>("FollowerCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_Actors_DisplayName_Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Actors_Slug");

                    b.HasIndex("EditorialRank", "PublishedAt", "Id")
                        .IsDescending(true, true, false)
                        .HasDatabaseName("IX_Actors_DiscoveryOrder");

                    b.ToTable("Actors", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Actors_AvatarStorageKey", "\"AvatarStorageKey\" !~ '(^/|[\\\\%?#:]|[[:cntrl:]]|(^|/)\\.{1,2}(/|$)|//)'");

                            t.HasCheckConstraint("CK_Actors_Counts", "\"FollowerCount\" >= 0 AND \"EditorialRank\" >= 0");

                            t.HasCheckConstraint("CK_Actors_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Actors_RequiredText", "char_length(btrim(\"DisplayName\")) > 0 AND char_length(btrim(\"Profession\")) > 0 AND char_length(btrim(\"Bio\")) > 0 AND char_length(btrim(\"AvatarStorageKey\")) > 0");

                            t.HasCheckConstraint("CK_Actors_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Actors_Timestamps", "\"PublishedAt\" > '-infinity' AND \"UpdatedAt\" >= \"PublishedAt\"");
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverAltText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("CoverAspectRatio")
                        .HasColumnType("double precision");

                    b.Property<string>("CoverStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("EditorialRank")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_Albums_Description_Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Tags")
                        .HasDatabaseName("IX_Albums_Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Albums_Title_Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ActorId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Albums_ActorId_Slug");

                    b.HasIndex("EditorialRank", "PublishedAt", "Id")
                        .IsDescending(true, true, false)
                        .HasDatabaseName("IX_Albums_DiscoveryOrder");

                    b.HasIndex("ActorId", "EditorialRank", "PublishedAt", "Id")
                        .IsDescending(false, true, true, false)
                        .HasDatabaseName("IX_Albums_Actor_DiscoveryOrder");

                    b.ToTable("Albums", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Albums_CoverStorageKey", "\"CoverStorageKey\" !~ '(^/|[\\\\%?#:]|[[:cntrl:]]|(^|/)\\.{1,2}(/|$)|//)'");

                            t.HasCheckConstraint("CK_Albums_Ids", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"ActorId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Albums_RequiredText", "char_length(btrim(\"Title\")) > 0 AND char_length(btrim(\"Description\")) > 0 AND char_length(btrim(\"CoverStorageKey\")) > 0 AND char_length(btrim(\"CoverAltText\")) > 0");

                            t.HasCheckConstraint("CK_Albums_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Albums_Timestamps", "\"PublishedAt\" > '-infinity' AND \"UpdatedAt\" >= \"PublishedAt\"");

                            t.HasCheckConstraint("CK_Albums_Values", "\"CoverAspectRatio\" > 0 AND \"CoverAspectRatio\" <> 'NaN'::double precision AND \"CoverAspectRatio\" <> 'Infinity'::double precision AND \"EditorialRank\" >= 0 AND cardinality(\"Tags\") <= 100");
                        });
                });

            modelBuilder.Entity("Catalog.Domain.LegacyRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("UX_LegacyRoutes_SourcePath");

                    b.ToTable("LegacyRoutes", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_LegacyRoutes_DestinationPath", "(\"DestinationPath\" = '/' OR \"DestinationPath\" ~ '^/([^/?#%\\\\]+/)*[^/?#%\\\\]+$') AND NOT \"DestinationPath\" ~ '(^|/)\\.{1,2}(/|$)' AND NOT \"DestinationPath\" ~ '[[:cntrl:]]' AND \"DestinationPath\" = btrim(\"DestinationPath\")");

                            t.HasCheckConstraint("CK_LegacyRoutes_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_LegacyRoutes_SourcePath", "\"SourcePath\" = lower(\"SourcePath\") AND (\"SourcePath\" = '/' OR \"SourcePath\" ~ '^/([^/?#%\\\\]+/)*[^/?#%\\\\]+$') AND NOT \"SourcePath\" ~ '(^|/)\\.{1,2}(/|$)' AND NOT \"SourcePath\" ~ '[[:cntrl:]]' AND \"SourcePath\" = btrim(\"SourcePath\")");

                            t.HasCheckConstraint("CK_LegacyRoutes_Timestamps", "\"CreatedAt\" > '-infinity' AND \"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Caption")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("EditorialRank")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Posts_Slug");

                    b.HasIndex("Tags")
                        .HasDatabaseName("IX_Posts_Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("AlbumId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_Posts_AlbumId_DisplayOrder");

                    b.ToTable("Posts", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Posts_Ids", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"AlbumId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Posts_Media", "(\"MediaType\" = 'Photo' AND \"DurationSeconds\" IS NULL AND \"MimeType\" ILIKE 'image/%') OR (\"MediaType\" = 'Video' AND \"DurationSeconds\" > 0 AND \"MimeType\" ILIKE 'video/%')");

                            t.HasCheckConstraint("CK_Posts_RequiredText", "char_length(btrim(\"StorageKey\")) > 0 AND char_length(btrim(\"MimeType\")) > 0 AND char_length(btrim(\"AltText\")) > 0");

                            t.HasCheckConstraint("CK_Posts_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Posts_StorageKey", "\"StorageKey\" !~ '(^/|[\\\\%?#:]|[[:cntrl:]]|(^|/)\\.{1,2}(/|$)|//)'");

                            t.HasCheckConstraint("CK_Posts_Timestamps", "\"PublishedAt\" > '-infinity' AND \"UpdatedAt\" >= \"PublishedAt\"");

                            t.HasCheckConstraint("CK_Posts_Values", "\"Width\" > 0 AND \"Height\" > 0 AND \"ByteSize\" > 0 AND \"DisplayOrder\" >= 0 AND \"EditorialRank\" >= 0 AND cardinality(\"Tags\") <= 100");
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Album", b =>
                {
                    b.HasOne("Catalog.Domain.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Catalog.Domain.Post", b =>
                {
                    b.HasOne("Catalog.Domain.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });
#pragma warning restore 612, 618
        }
    }
}
